### ISSUE TITLE
Failure to parse logical parameter statement

### ISSUE THREAD

**Issue by johnmauff** [ROCmSoftwarePlatform/gpufort#32]
The develop-acc branch version of gpufort fails to parse the following file:  

`program test1
   logical, parameter :: dosfcflx = .true.
end program test1
`

**Comment by domcharrier** [comment]
Can reproduce parsing error but diagnosis seems wrong as:
```
program test1
  ! logical, parameter :: dosfcflx = .true.   ! not working
  ! logical :: dosfcflx = .true.              ! not working
  logical,parameter :: dosfcflx               ! works!
end program test1
```
In general, it seems that `=` and `=>` cause the observed issues.

Thanks for your bug reports, @johnmauff

**Comment by domcharrier** [comment]
Please recheck with the latest `develop-acc` branch.

**Comment by johnmauff** [comment]
Confirmed that your code update fixes the bug.  Your changes for #32 and #33 have reduced the number of files that do not parse properly from 45 to 40. Thanks
