### ISSUE TITLE
Failure to parse null pointer assignment in declaration

### ISSUE THREAD

**Issue by johnmauff** [ROCmSoftwarePlatform/gpufort#33]
The develop-acc branch fails to properly parse the following bit of code:

`program test1
   real, dimension(:,:,:,:), pointer :: tauaer_sw=>null()
end program test1 
`

**Comment by domcharrier** [comment]
Confirmed.

**Comment by domcharrier** [comment]
Please recheck with the latest `develop-acc` branch.

**Comment by johnmauff** [comment]
Just confirmed that your code update addresses this bug
