### ISSUE TITLE
Parsing error with comment after line continuation character

### ISSUE THREAD

**Issue by johnmauff** [ROCmSoftwarePlatform/gpufort#34]
The following code will generate a parsing error:

`program test1
   integer, parameter :: ims = 12,ime=16,jms=1,jme=10
   REAL,  DIMENSION(ims:ime, jms:jme), INTENT(OUT) ::                   & ! Does not like a comment here
                                        HEAT2D                            ! What about here 
end program test1 
`

**Comment by domcharrier** [comment]
Confirmed.

**Comment by domcharrier** [comment]
@johnmauff  Should be addressed by latest `develop-acc` changes. Please confirm on your end.

**Comment by johnmauff** [comment]
@domcharrier Thanks for the update.  Unfortunately, this modification appears to trigger an indexing error in the split_fortran_line function see issue #38.  As a result, this update does not reduce the number of files that generate errors in my application.
